name: Atualização diária dos dados

on:
  workflow_dispatch:
  schedule:
    - cron: '5 12,13,18,23 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
        
      - name: Instalar pacotes do Python
        run: pipenv install
        
      - name: Executar script
        run: pipenv run python runner.py
        working-directory: ./scripts

      - name: Commit de arquivos
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Arquivos atualizados" --allow-empty)

      - name: Push dos commits
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
