name: Atualização diária dos dados

on:
  schedule:
    - cron: '5 3,12,13,18,23 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
        
      - name: Instalar pacotes do Python
        run: pipenv install
        
      - name: Executar script
        run: pipenv run python scripts/runner.py
